# Generated by Django 4.2.7 on 2023-11-10 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.JSONField(default=dict)),
                ('counties', models.TextField(help_text='List of counties where program is available')),
                ('income_limits', models.JSONField(default=dict)),
                ('liquid_asset_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_score_minimum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.CharField(max_length=250)),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(850)])),
                ('liquid_assets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household_size', models.IntegerField()),
                ('is_first_time_buyer', models.BooleanField(default=False)),
                ('is_three_year_buyer', models.BooleanField(default=False)),
                ('is_female_head_of_household', models.BooleanField(default=False)),
                ('is_PEN', models.BooleanField(default=False)),
            ],
        ),
    ]
